#! /bin/sh
# postrm script for xrdp
#
# see: dh_installdeb(1)

set -e

#DEBHELPER#

case "$1" in
    purge)
	# We delete user and group
	deluser --system xrdp || true
	delgroup --system xrdp || true

        rm -rf /etc/xrdp /var/run/xrdp
    ;;
    *)
    ;;
esac

exit 0

