#!/bin/sh
#-
# Script to compile / recompile xrdp PulseAudio modules.
# The caller needs to be root or a member of the sudo group.
# Also, /etc/apt/sources.list must contain a valid deb-src line.
#
# © 2017 Wolfgang Schweer <wschweer@arcor.de>
# © 2017 Dominik George <nik@naturalnet.de>
#
# Published under the "GPL v2 or any later version" license.
#-
# This script downloads the Debian source package for pulseaudio
# corresponding to the installed binary version, then builds the PulseAudio
# module for xrdp and installs it.

set -e

# Get an empty temporary directory
tmp=$(mktemp -d); cd "$tmp"

# Determine versions of pulseaudio and xrdp
pulseaudio_version=$(dpkg-query -W -f='${source:Version}' pulseaudio)
pulseaudio_upstream_version=$(dpkg-query -W -f='${source:Upstream-Version}' pulseaudio)

# FIXME determine automagically
mirror="http://ftp.debian.org/debian/"

# Download source packages
dget "${mirror}pool/main/p/pulseaudio/pulseaudio_${pulseaudio_version}.dsc"

# Configure pulseaudio source
cd "pulseaduio-$pulseaudio_upstream_version"
./configure
cd -

# Build PulseAudio module
cd "/usr/src/xrdp-pulse"
make PULSE_DIR="$tmp/pulseaduio-$pulseaudio_upstream_version"

# Install modules to Pulseaudio modules directory
install -t "/usr/lib/pulse-$pulseaudio_upstream_version/modules/" -m 644 *.so

# Clean up
make clean
cd /
rm -rf "$tmp"
